# Generated by Django 4.0.4 on 2022-06-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='observations',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
