# Generated by Django 4.0.4 on 2022-06-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_logbook_observations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='observations',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
