# Generated by Django 4.0.4 on 2022-06-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0003_alter_logbook_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='nb_personne',
            field=models.CharField(choices=[('Solo', 'Duo')], default='', max_length=4),
        ),
    ]
