# Generated by Django 4.0.4 on 2022-06-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0004_logbook_nb_personne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='nb_personne',
            field=models.CharField(choices=[('Solo', 'Duo')], default='Solo', max_length=4),
        ),
    ]
