# Generated by Django 4.0.4 on 2022-06-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0005_alter_logbook_nb_personne'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logbook',
            name='nb_personne',
        ),
        migrations.AddField(
            model_name='logbook',
            name='duo',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
