# Generated by Django 4.0.4 on 2022-06-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0008_alter_logbook_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='user',
            field=models.CharField(default='noname', max_length=50),
        ),
    ]
