# Generated by Django 4.0.4 on 2022-08-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0009_alter_logbook_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='start',
            field=models.DateField(default=-3600),
        ),
    ]
