# Generated by Django 4.0.4 on 2022-08-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0010_alter_logbook_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='start',
            field=models.DateTimeField(default=-3600),
        ),
    ]
