# Generated by Django 4.0.4 on 2022-08-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0011_alter_logbook_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='start',
            field=models.CharField(max_length=50),
        ),
    ]
