# Generated by Django 4.0.4 on 2022-08-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0012_alter_logbook_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='aircraft',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='from_airport',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='ident',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='observations',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='start',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='to_airport',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='user',
            field=models.CharField(default='noname', max_length=20),
        ),
    ]
