# Generated by Django 4.0.4 on 2022-08-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0013_alter_logbook_aircraft_alter_logbook_from_airport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='observations',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
