# Generated by Django 4.0.4 on 2022-05-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useCallSign', models.CharField(help_text='Callsign', max_length=20, null=True)),
                ('userName', models.CharField(help_text='Nom', max_length=50)),
                ('userEmail', models.EmailField(help_text='email', max_length=50)),
                ('userPassword', models.EmailField(help_text='password', max_length=50)),
            ],
        ),
    ]
