# Generated by Django 4.0.4 on 2022-05-12 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hangar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='useCallSign',
            new_name='userCallSign',
        ),
    ]
