# Generated by Django 4.0.4 on 2022-05-13 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hangar', '0002_rename_usecallsign_users_usercallsign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='userPassword',
        ),
    ]
