# Generated by Django 4.0.4 on 2022-05-13 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hangar', '0004_logbook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logbook',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
